# This is a basic workflow to help you get started with Actions

name: quotes ar twitter bot

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy python-dotenv supabase
      - name: execute py script 
        run: |
          python post_tweet_ar.py
        env:
          QUOTES_TWITER_BOT_CONSUMER_KEY_1: ${{secrets.QUOTES_TWITER_BOT_CONSUMER_KEY_1}}
          QUOTES_TWITER_BOT_CONSUMER_SECRET_1: ${{secrets.QUOTES_TWITER_BOT_CONSUMER_SECRET_1}}
          QUOTES_AR_TWITER_BOT_ACCESS_TOKEN: ${{secrets.QUOTES_AR_TWITER_BOT_ACCESS_TOKEN}}
          QUOTES_AR_TWITER_BOT_ACCESS_TOKEN_SECRET: ${{secrets.QUOTES_AR_TWITER_BOT_ACCESS_TOKEN_SECRET}}
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
