# This is a basic workflow to help you get started with Actions

name: quotes de twitter bot

# Controls when the workflow will run
#on:
#  schedule:
#    - cron: "40 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy python-dotenv supabase
      - name: execute py script 
        run: |
          python post_tweet_de.py
        env:
          QUOTES_TWITER_BOT_CONSUMER_KEY_: ${{secrets.QUOTES_TWITER_BOT_CONSUMER_KEY_}}
          QUOTES_TWITER_BOT_CONSUMER_SECRET_: ${{secrets.QUOTES_TWITER_BOT_CONSUMER_SECRET_}}
          QUOTES_DE_TWITER_BOT_ACCESS_TOKEN: ${{secrets.QUOTES_DE_TWITER_BOT_ACCESS_TOKEN}}
          QUOTES_DE_TWITER_BOT_ACCESS_TOKEN_SECRET: ${{secrets.QUOTES_DE_TWITER_BOT_ACCESS_TOKEN_SECRET}}
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
